<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Celery on Avelino</title>
    <link>https://avelino.run/tags/celery/</link>
    <description>Recent content in Celery on Avelino</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Mon, 30 Mar 2015 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://avelino.run/tags/celery/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Cron dentro do Django com Celery</title>
      <link>https://avelino.run/cron-dentro-do-django-com-celery/</link>
      <pubDate>Mon, 30 Mar 2015 00:00:00 +0000</pubDate>
      
      <guid>https://avelino.run/cron-dentro-do-django-com-celery/</guid>
      <description>Ontem na parte da noite conversando com um conhecido ele falou que estava usando em um projeto o Celery, como ainda não conhecia vamos estudar este projeto. Gostei da forma que ele trabalha e como ele integra com o Django. | Tenho em um projeto uma fila de processamento só que foi desenvolvido por mim e não tem todos os recursos que o Celery tem.
Vou explicar como usar o Celery com o Django em um exemplo simples, e como sempre basta usar a criatividade para desenvolver a sua necessidade.</description>
    </item>
    
    <item>
      <title>Problema com Celery &#34;process exiting with exitcode 1&#34;</title>
      <link>https://avelino.run/problema-com-celery-process-exiting-with-exitcode-1/</link>
      <pubDate>Sun, 26 Dec 2010 00:00:00 +0000</pubDate>
      
      <guid>https://avelino.run/problema-com-celery-process-exiting-with-exitcode-1/</guid>
      <description>Hoje estava rodando o Celery em um projeto e me deparei com um problema, o &amp;ldquo;process exiting with exitcode 1&amp;rdquo; quando dava start no Celery:
[root@xen-01 gonow]# python2.7 manage.py celeryd -v 2 -B -s celery -E -l INFO [2010-12-16 09:18:13,184: WARNING/MainProcess] celery@xen-01 v2.1.3 is starting. [2010-12-16 09:18:13,185: WARNING/MainProcess] /usr/local/lib/python2.7/site-packages/celery-2.1.3-py2.7.egg/celery/apps/ worker.py:107: UserWarning: Running celeryd with superuser privileges is not encouraged! &amp;quot;Running celeryd with superuser privileges is not encouraged!&amp;quot;) [2010-12-16 09:18:13,185: WARNING/MainProcess] /usr/local/lib/python2.</description>
    </item>
    
  </channel>
</rss>